sudo: false

language: node_js

node_js:
  - '0.10'
  - '0.12'
  - '4'
  - '5'

addons:
  apt:
    packages:
    - aria2

before_script:
  - npm install -g mocha standard
  - npm test
  - nohup aria2c --enable-rpc --rpc-listen-all=true --rpc-allow-origin-all &
  - npm run integration
  - cat nohup.out
